### ISSUE TITLE
Ejercicio#1 - 3. Realizar la suma de n números reales ingresados por terminal y calcular su media.

### ISSUE THREAD

**Issue by guelo2019** [EMTSTISPC/Grupo13#10]
Desarrollar el código para cumplir con la consigna del punto 3.

**Comment by OscarAGazzola** [comment]
Este ejercicio lo programamos en Python?
Luego pegamos la sentencia?

**Comment by guelo2019** [comment]
No hay que hacer en C++, se supone que son Prácticas de I/O en sistemas embebidos. por lo tanto se programa en C++ para una placa de desarrollo Arduino por ejemplo.

**_Bienvenido a las practicas con sistemas embebidos, en la misma
desarrollaremos la ejercitación del lenguaje CPP para sistemas embebidos
con VsCode @ PlatformIO, con el framework de Arduino.
La modalidad será la siguiente:
Cada practica se desarrollará en forma grupal, debiendo subir el desarrollo
de la misma al repositorio ( respetando la estructura de monorepositorio)
establecido por grupo. Los ejercicios serán implementados de forma que a
cada integrante le corresponda 1 o más tareas (issues); por lo que deberán
crear el proyecto correspondiente, con la documentación asociada si hiciera
falta, y asignar los issues por integrante. De esta forma quedara
documentada la colaboración de cada alumno._**

**Comment by OscarAGazzola** [comment]
#include <Arduino.h>

int n; 
float media;

void setup() {
  Serial.begin(9600);
}


void loop() {
  media = 0;
  Serial.println ("Ingrese cuantos datos desea calcular:");
  while (!Serial.available()); // Esperamos a que entre algo por el serial.
  n = (Serial.readString()).toInt(); //recoge el numero de datos
  Serial.print ("Datos a procesar = ");
  Serial.println (n);
  int numeros [n]; //creamos una matriz de n variables
  // lectura de n datos
  for (int x = 0; x <= n - 1; x++) {
    Serial.print ("Dato ");
    Serial.print (x + 1);
    Serial.print (" = ");
    while (!Serial.available()); // Esperamos a que entre algo por el serial.
    numeros [x] = (Serial.readString()).toInt(); //Memoriza los datos
    Serial.println (numeros [x]);
  }
  for (int x = 0; x <= n - 1; x++) { //suma todos los datos
    media = media + numeros [x];
  }
  Serial.print ("La media de datos es =");
  media = media / n; 
  Serial.println (media);
  Serial.println ();
  Serial.println ();
}

**Comment by gonaiot** [comment]
@OscarAGazzola 
Estimado Oscar, su codigo funciona. Puede mejorarse, pero el intercambio de dialogo con @guelo2019 esta muy bien. continuen asi.
