### ISSUE TITLE
Ejercicio#1 - 4. Pedir un valor entre 0 y 255, para controlar el brillo de un diodo led.

### ISSUE THREAD

**Issue by guelo2019** [EMTSTISPC/Grupo13#11]
Realizar el código que cumpla con la consigna del enunciado del punto4.

**Comment by Ezequiel0681** [comment]
[Ejercicio1Punto4.pdf](https://github.com/EMTSTISPC/Grupo13/files/9411525/Ejercicio1Punto4.pdf)

**Comment by Ezequiel0681** [comment]
Realizado

**Comment by gonaiot** [comment]
@Ezequiel0681 
Estimado Ezequiel, el ejercicio realizado no termino en la carpeta que corresponde. @guelo2019 Que sucedio?. 
Aun asi participo en el desarrollo del flujo del repositorio. El codigo en si, que ud realizo, asi como esta no va a funcionar. Es mejorable, pero la idea del codigo esta bien. Debe mejorar estos aspectos.
