### ISSUE TITLE
Ejercicio #2 - Investigar punto 1

### ISSUE THREAD

**Issue by guelo2019** [EMTSTISPC/Grupo13#4]
**Investigar y documentar**
1. Explicar detalladamente el funcionamiento del terminal virtual en proteus, del monitor serie en VsCode@platformIO y del monitor serie en el ide de Arduino.

**Comment by Ezequiel0681** [comment]
[Ejercitación Evaluativa.pdf](https://github.com/EMTSTISPC/Grupo13/files/9410448/Ejercitacion.Evaluativa.pdf)

**Comment by Ezequiel0681** [comment]
Ejercicio N2

**Comment by Ezequiel0681** [comment]
realizado

**Comment by gonaiot** [comment]
@guelo2019 @Ezequiel0681 
Estimados, lo mismo que antes, el material no se plasmo en el repo correctamente.
